trigger: none

pr: none

schedules:
  - cron: "0 6 * * 6"
    displayName: Saturday deploy
    branches:
      include:
        - main
    always: true

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self

- task: Bash@3
  inputs:
    targetType: inline
    script: |
      sudo apt-get update
      sudo apt-get install -y unzip curl

      TERRAFORM_VERSION="1.8.5"

      curl -LO https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
      unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip
      sudo mv terraform /usr/local/bin/

      terraform version

- task: AzureCLI@2
  inputs:
    azureSubscription: 'azure-resource-manager-connection'
    scriptType: bash
    scriptLocation: inlineScript
    workingDirectory: $(System.DefaultWorkingDirectory)/project1-Azure-Lab
    inlineScript: |
      terraform init
      terraform plan
      terraform apply -auto-approve