trigger: none

pr: none

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self

- task: Bash@3
  inputs:
    targetType: inline
    script: |
      sudo apt-get update
      sudo apt-get install -y unzip curl

      TERRAFORM_VERSION="1.8.5"

      curl -LO https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
      unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip
      sudo mv terraform /usr/local/bin/

      terraform version

- task: AzureCLI@2
  inputs:
    azureSubscription: 'azure-resource-manager-connection'
    scriptType: bash
    scriptLocation: inlineScript
    workingDirectory: $(System.DefaultWorkingDirectory)/project1-Azure-Lab/Versions/V1
    inlineScript: |
      export ARM_USE_OIDC=true
      export ARM_CLIENT_ID=$(client_id)
      export ARM_CLIENT_SECRET=$(client_secret)
      export ARM_TENANT_ID=$(tenant_id)
      export ARM_SUBSCRIPTION_ID=$(sub_id)

      export TF_VAR_allowed_ip_ssh="$(vpn_ip)"

      terraform init
      terraform plan
      terraform apply -auto-approve